drop database if exists DBSA;
create database DBSA;
use DBSA;



CREATE TABLE USUARIO(
	ID_USUARIO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    SENHA VARCHAR(32) NOT NULL,
    TIPO_USUARIO VARCHAR(7) NOT NULL,
    ATIVO VARCHAR(7) NOT NULL,
    PRIMARY KEY(ID_USUARIO)
);

CREATE TABLE RECEITA(
	ID_RECEITA INT NOT NULL AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
	-- TIPO VARCHAR(45) NOT NULL,
    IMAGEM VARCHAR(1000),
    TITULO VARCHAR(100) NOT NULL,
    PORCAO VARCHAR(100),
    TEMPO VARCHAR(30),
    ATIVA VARCHAR(7) NOT NULL,
    PRIMARY KEY(ID_RECEITA, ID_USUARIO),
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE INGREDIENTE(
	ID_INGREDIENTE INT NOT NULL AUTO_INCREMENT,
    ID_RECEITA INT NOT NULL,
	NOME VARCHAR(50) NOT NULL,
    
    PRIMARY KEY(ID_INGREDIENTE, ID_RECEITA),
    FOREIGN KEY(ID_RECEITA) REFERENCES RECEITA(ID_RECEITA)
);


CREATE TABLE PASSOS(
	ID_PASSOS INT NOT NULL AUTO_INCREMENT,
    ID_RECEITA INT NOT NULL,
    DESCRICAO VARCHAR(100),
    NUMERO INT,
    PRIMARY KEY(ID_PASSOS,ID_RECEITA),
    FOREIGN KEY(ID_RECEITA) REFERENCES RECEITA(ID_RECEITA)
);




INSERT INTO USUARIO(ID_USUARIO, NOME, EMAIL, SENHA, TIPO_USUARIO, ATIVO)
VALUES (1, 'Mateus Rocha', 'matheus@gmail.com', 'cabrito123', 'USUARIO', "false");
INSERT INTO USUARIO(ID_USUARIO, NOME, EMAIL, SENHA, TIPO_USUARIO, ATIVO)
VALUES (2, 'João Ricardo', 'jonas@gmail.com', 'monica123', 'USUARIO', "true");
INSERT INTO USUARIO(ID_USUARIO, NOME, EMAIL, SENHA, TIPO_USUARIO, ATIVO)
VALUES (3, 'Dudu Gonzalez', 'dudu@gmail.com', 'dudu1234', 'USUARIO', "true");
INSERT INTO USUARIO(ID_USUARIO, NOME, EMAIL, SENHA, TIPO_USUARIO, ATIVO)
VALUES (4, 'Admin Marcos', 'marcos@gmail.com', 'admin123', 'ADMIN', "true");

INSERT INTO RECEITA(ID_USUARIO, IMAGEM, TITULO, PORCAO, TEMPO, ATIVA)
VALUES (4, 'https://s2.glbimg.com/DnsDp5_cwUYLCQ8O3WqsKWaBVMU=/0x0:300x225/984x0/smart/filters:strip_icc()/s.glbimg.com/po/rc/media/2013/02/20/10_17_21_740_Banana_Frita.jpg', 'Banana Frita', '1','10min', 'true');

INSERT INTO INGREDIENTE(ID_RECEITA, NOME) 
VALUES(1, '2 bananas');
INSERT INTO INGREDIENTE(ID_RECEITA, NOME) 
VALUES(1, '1 colher de manteiga');

INSERT INTO PASSOS(ID_RECEITA, DESCRICAO, NUMERO)
VALUES (1, 'Ligue o fogo e coloque a manteiga', 1);
INSERT INTO PASSOS(ID_RECEITA, DESCRICAO, NUMERO)
VALUES (1, 'Após a manteiga derreter, coloque as bananas', 2);
INSERT INTO PASSOS(ID_RECEITA, DESCRICAO, NUMERO)
VALUES (1, 'Após elas dourarem, coloque em um recipiente', 3);
INSERT INTO PASSOS(ID_RECEITA, DESCRICAO, NUMERO)
VALUES (1, 'Sirva-se', 4);


INSERT INTO RECEITA(ID_USUARIO, IMAGEM, TITULO, PORCAO, TEMPO, ATIVA)
VALUES (4, 'https://www.sabornamesa.com.br/media/k2/items/cache/c501a702ef05e90d163a1eeeb1633357_XL.jpg', 'Pastel Frito', '10', '20min', 'true');

INSERT INTO INGREDIENTE(ID_RECEITA, NOME) 
VALUES(2, 'massa pronta de pastel');
INSERT INTO INGREDIENTE(ID_RECEITA, NOME) 
VALUES(2, '250g de carne moída');
INSERT INTO INGREDIENTE(ID_RECEITA, NOME) 
VALUES(2, '300ml de óleo de soja');

INSERT INTO PASSOS(ID_RECEITA, DESCRICAO, NUMERO)
VALUES (2, 'Abra a massa dos pastéis e coloque a carne moída já cozida', 1);
INSERT INTO PASSOS(ID_RECEITA, DESCRICAO, NUMERO)
VALUES (2, 'Em uma panela, adicione o óleo e ligue no fogo alto', 2);
INSERT INTO PASSOS(ID_RECEITA, DESCRICAO, NUMERO)
VALUES (2, 'Coloque os pastéis e deixe por 15 minutos', 3);
INSERT INTO PASSOS(ID_RECEITA, DESCRICAO, NUMERO)
VALUES (2, 'Retire os pastéis', 4);
INSERT INTO PASSOS(ID_RECEITA, DESCRICAO, NUMERO)
VALUES (2, 'Sirva-se',  5);



/* * FROM RECEITA;
SELECT * FROM INGREDIENTE;
SELECT * FROM PASSOS;
*/
